-- Drop all existing tables
DROP TABLE IF EXISTS activities CASCADE;
DROP TABLE IF EXISTS supporting_series CASCADE;
DROP TABLE IF EXISTS local_attractions CASCADE;
DROP TABLE IF EXISTS podium_results CASCADE;
DROP TABLE IF EXISTS circuit_details CASCADE;
DROP TABLE IF EXISTS airports CASCADE;
DROP TABLE IF EXISTS ticket_pricing CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS saved_itineraries CASCADE;
DROP TABLE IF EXISTS races CASCADE;
DROP TABLE IF EXISTS circuits CASCADE;

-- Create circuits table
CREATE TABLE IF NOT EXISTS circuits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  location TEXT NOT NULL,
  country TEXT NOT NULL,
  latitude NUMERIC(10,7) NOT NULL,
  longitude NUMERIC(10,7) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create races table
CREATE TABLE IF NOT EXISTS races (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  circuit_id UUID NOT NULL REFERENCES circuits(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  date TIMESTAMP WITH TIME ZONE NOT NULL,
  season INTEGER NOT NULL,
  round INTEGER NOT NULL,
  country TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create saved_itineraries table
CREATE TABLE IF NOT EXISTS saved_itineraries (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id TEXT NOT NULL,
  race_id UUID NOT NULL REFERENCES races(id) ON DELETE CASCADE,
  itinerary JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create tickets table
CREATE TABLE IF NOT EXISTS tickets (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  race_id UUID NOT NULL REFERENCES races(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  ticket_type TEXT NOT NULL,
  availability TEXT NOT NULL,
  days_included JSONB NOT NULL,
  is_child_ticket BOOLEAN NOT NULL DEFAULT false,
  reseller_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_by TEXT
);

-- Create ticket_pricing table
CREATE TABLE IF NOT EXISTS ticket_pricing (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticket_id INTEGER NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  price DECIMAL(10,2) NOT NULL,
  currency TEXT NOT NULL,
  valid_from TIMESTAMP WITH TIME ZONE NOT NULL,
  valid_to TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_by TEXT
);

-- Create airports table
CREATE TABLE IF NOT EXISTS airports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  circuit_id UUID NOT NULL REFERENCES circuits(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  distance TEXT NOT NULL,
  transfer_time TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- Create circuit_details table
CREATE TABLE IF NOT EXISTS circuit_details (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  circuit_id UUID NOT NULL REFERENCES circuits(id) ON DELETE CASCADE,
  length DECIMAL(10,3) NOT NULL,
  corners INTEGER NOT NULL,
  drs_zones INTEGER NOT NULL,
  lap_record_time TEXT,
  lap_record_year INTEGER,
  lap_record_driver TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- Create podium_results table
CREATE TABLE IF NOT EXISTS podium_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  circuit_id UUID NOT NULL REFERENCES circuits(id) ON DELETE CASCADE,
  position INTEGER NOT NULL CHECK (position BETWEEN 1 AND 3),
  driver TEXT NOT NULL,
  team TEXT NOT NULL,
  year INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- Create local_attractions table
CREATE TABLE IF NOT EXISTS local_attractions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  circuit_id UUID NOT NULL REFERENCES circuits(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- Create supporting_series table
CREATE TABLE IF NOT EXISTS supporting_series (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  race_id UUID NOT NULL REFERENCES races(id) ON DELETE CASCADE,
  series TEXT NOT NULL,
  round INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- Create activities table
CREATE TABLE IF NOT EXISTS activities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  itinerary_id INTEGER NOT NULL REFERENCES saved_itineraries(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  price_amount DECIMAL(10,2),
  price_currency TEXT,
  rating DECIMAL(3,1),
  category TEXT,
  distance TEXT,
  duration TEXT,
  location_lat DECIMAL(10,8),
  location_lng DECIMAL(11,8),
  time_slot TEXT,
  description TEXT,
  visit_duration TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- Add triggers to update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_circuits_updated_at
    BEFORE UPDATE ON circuits
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_races_updated_at
    BEFORE UPDATE ON races
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_saved_itineraries_updated_at
    BEFORE UPDATE ON saved_itineraries
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tickets_updated_at
    BEFORE UPDATE ON tickets
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_ticket_pricing_updated_at
    BEFORE UPDATE ON ticket_pricing
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_airports_updated_at
    BEFORE UPDATE ON airports
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_circuit_details_updated_at
    BEFORE UPDATE ON circuit_details
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_podium_results_updated_at
    BEFORE UPDATE ON podium_results
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_local_attractions_updated_at
    BEFORE UPDATE ON local_attractions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_supporting_series_updated_at
    BEFORE UPDATE ON supporting_series
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_activities_updated_at
    BEFORE UPDATE ON activities
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Create temporary tables for data migration
CREATE TEMPORARY TABLE races_old (
  id INTEGER,
  name TEXT,
  circuit TEXT,
  country TEXT,
  date TIMESTAMP WITH TIME ZONE,
  image_url TEXT,
  description TEXT,
  transport_info JSONB,
  weather_info JSONB,
  nearest_airports JSONB,
  city TEXT,
  latitude TEXT,
  longitude TEXT,
  schedule JSONB,
  ticket_info JSONB,
  circuit_info JSONB,
  last_year_podium JSONB,
  track_map_url TEXT,
  status TEXT,
  slug TEXT,
  local_attractions JSONB,
  suggested_itineraries JSONB,
  availability TEXT,
  price DECIMAL(10,2),
  season TEXT,
  supporting_series JSONB,
  is_sprint_weekend BOOLEAN,
  weekend_start TIMESTAMP WITH TIME ZONE,
  weekend_end TIMESTAMP WITH TIME ZONE
);

CREATE TEMPORARY TABLE saved_itineraries_old (
  id INTEGER,
  race_id INTEGER,
  user_id INTEGER,
  name TEXT,
  activities JSONB,
  created_at TIMESTAMP WITH TIME ZONE,
  share_token TEXT,
  date TIMESTAMP WITH TIME ZONE
);

-- Insert races data
INSERT INTO races_old VALUES (
    20,
    'Singapore Grand Prix 2025',
    'Marina Bay Street Circuit',
    'Singapore',
    '2025-10-10T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Singapore.jpg',
    'Night race through the illuminated streets of Marina Bay.',
    '{"mrt":"Circle and Downtown lines to Promenade station","taxi":"Available throughout city"}'::jsonb,
    '{"humidity":"85%","rainfall":"High","averageTemp":"28°C"}'::jsonb,
    '[{"code":"SIN","name":"Singapore Changi Airport","distance":"20km","transferTime":"20-30 minutes"}]'::jsonb,
    'Singapore',
    '1.2914',
    '103.8644',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"5.063","corners":23,"drsZones":3,"lapRecord":{"time":"1:41.905","year":2018,"driver":"Lewis Hamilton"}}'::jsonb,
    '[{"team":"Ferrari","driver":"Carlos Sainz","position":1},{"team":"McLaren","driver":"Lando Norris","position":2},{"team":"Mercedes","driver":"Lewis Hamilton","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Gardens by the Bay","description":"Futuristic nature park"},{"name":"Marina Bay Sands","description":"Iconic hotel and skypark"}]'::jsonb,
    '[]'::jsonb,
    'limited',
    3845.00,
    'fall',
    '[{"round":13,"series":"F2"},{"round":6,"series":"F1 Academy"}]'::jsonb,
    false,
    '2025-10-09T23:00:00.000Z',
    '2025-10-11T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    13,
    'Miami Grand Prix 2025',
    'Miami International Autodrome',
    'United States',
    '2025-05-09T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Miami.jpg',
    'Racing around Hard Rock Stadium in the heart of Miami Gardens.',
    '{"shuttle":"Free shuttle service from designated parking areas","rideshare":"Dedicated pickup/dropoff zones"}'::jsonb,
    '{"humidity":"75%","rainfall":"Low","averageTemp":"27°C"}'::jsonb,
    '[{"code":"MIA","name":"Miami International Airport","distance":"25km","transferTime":"30-40 minutes"}]'::jsonb,
    'Miami',
    '25.9581',
    '-80.2389',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"5.412 km","corners":19,"drsZones":3,"lapRecord":{"time":"1:29.708","year":2023,"driver":"Max Verstappen"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"Red Bull Racing","driver":"Sergio Perez","position":2},{"team":"Aston Martin","driver":"Fernando Alonso","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"South Beach","description":"Famous beach and entertainment district"},{"name":"Wynwood Walls","description":"Outdoor museum of street art"}]'::jsonb,
    '[]'::jsonb,
    'available',
    3633.00,
    'spring',
    '[{"round":6,"series":"F2"},{"round":4,"series":"F1 Academy"},{"round":6,"series":"F1 Sprint"}]'::jsonb,
    true,
    '2025-05-08T23:00:00.000Z',
    '2025-05-10T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    14,
    'Emilia Romagna Grand Prix 2025',
    'Autodromo Enzo e Dino Ferrari',
    'Italy',
    '2025-05-23T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Emilia_Romagna.jpg',
    'Historic Italian circuit named after Ferrari''s founder and his son.',
    '{"taxi":"Available at airport and circuit","shuttle":"Regular service from Bologna and Imola stations"}'::jsonb,
    '{"humidity":"65%","rainfall":"Moderate","averageTemp":"22°C"}'::jsonb,
    '[{"code":"BLQ","name":"Bologna Guglielmo Marconi Airport","distance":"40km","transferTime":"45-50 minutes"}]'::jsonb,
    'Imola',
    '44.3439',
    '11.7167',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"4.909 km","corners":19,"drsZones":1,"lapRecord":{"time":"1:15.484","year":2020,"driver":"Lewis Hamilton"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"Red Bull Racing","driver":"Sergio Perez","position":2},{"team":"McLaren","driver":"Lando Norris","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Museo Checco Costa","description":"Racing museum at the circuit"},{"name":"Historic Center of Imola","description":"Medieval town center"}]'::jsonb,
    '[]'::jsonb,
    'available',
    1763.00,
    'spring',
    '[{"round":7,"series":"F2"},{"round":4,"series":"F3"}]'::jsonb,
    false,
    '2025-05-22T23:00:00.000Z',
    '2025-05-24T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    3,
    'Bahrain Grand Prix 2025',
    'Bahrain International Circuit',
    'Bahrain',
    '2025-04-12T22:00:00.000Z',
    'https://picsum.photos/1920/1080',
    'The season opener under the lights of Bahrain',
    '{"public":{"options":[],"description":""},"parking":{"options":[],"description":""}}'::jsonb,
    '{"practice1":{"humidity":"45","windSpeed":"15","conditions":"Clear","temperature":"24","precipitation":"0"}}'::jsonb,
    '[{"code":"BAH","name":"Bahrain International Airport","distance":"12km","transferTime":"15 mins"}]'::jsonb,
    'Sakhir',
    '26.0325',
    '50.5106',
    '{"race":"2025-03-02 18:00","practice1":"2025-02-28 13:00","practice2":"2025-02-28 17:00","practice3":"2025-03-01 14:00","qualifying":"2025-03-01 17:00"}'::jsonb,
    '{"general":{"price":"150","availability":"medium"},"grandstand":{"price":"450","availability":"high"}}'::jsonb,
    '{"length":"5.412 km","corners":15,"drsZones":3,"lapRecord":{"time":"1:31.447","year":2005,"driver":"Pedro de la Rosa"}}'::jsonb,
    '{"first":{"team":"Red Bull Racing","driver":"Max Verstappen"},"third":{"team":"Aston Martin","driver":"Fernando Alonso"},"second":{"team":"Red Bull Racing","driver":"Sergio Perez"}}'::jsonb,
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Bahrain_Circuit.png',
    'upcoming',
    'bahrain-grand-prix-2025',
    '[{"id":"1","name":"City Walking Tour","type":"guided","price":{"amount":30,"currency":"USD"},"rating":4.5,"category":"cultural","distance":"2 km from circuit","duration":"2.5 hr","location":{"lat":40.7128,"lng":-74.006},"description":"Explore historic landmarks and architecture"},{"id":"2","name":"Karting Experience","type":"activity","price":{"amount":45,"currency":"USD"},"rating":4.8,"category":"sports","distance":"5 km from circuit","duration":"1.5 hr","location":{"lat":40.7228,"lng":-74.016},"description":"Race on a professional karting circuit"},{"id":"3","name":"Local Food Tour","type":"guided","price":{"amount":55,"currency":"USD"},"rating":4.6,"category":"dining","distance":"1.5 km from circuit","duration":"3 hr","location":{"lat":40.7328,"lng":-74.026},"description":"Taste authentic local cuisine and street food"},{"id":"4","name":"Racing Museum","type":"attraction","price":{"amount":25,"currency":"USD"},"rating":4.3,"category":"entertainment","distance":"3 km from circuit","duration":"2 hr","location":{"lat":40.7428,"lng":-74.036},"description":"Learn about local motorsport history"},{"id":"5","name":"Motorsport Mall","type":"shopping","price":{"amount":0,"currency":"USD"},"rating":4.2,"category":"shopping","distance":"4 km from circuit","duration":"1.5 hr","location":{"lat":40.7528,"lng":-74.046},"description":"F1 merchandise and local souvenirs"}]'::jsonb,
    '[]'::jsonb,
    'limited',
    5258.00,
    'spring',
    '[{"round":2,"series":"F2"},{"round":2,"series":"F3"}]'::jsonb,
    false,
    '2025-04-10T23:00:00.000Z',
    '2025-04-12T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    5,
    'Australian Grand Prix 2025',
    'Albert Park Circuit',
    'Australia',
    '2025-03-16T00:00:00.000Z',
    'https://www.racetechmag.com/wp-content/uploads/2019/07/2019australianf1gpstart.jpg',
    'Racing through Melbourne''s beautiful Albert Park',
    '{"public":{"options":["Tram service","Special event buses"],"description":"Extensive public transport options"},"parking":{"options":["Pre-booking available"],"description":"Official parking zones"}}'::jsonb,
    '{}'::jsonb,
    '[{"code":"MEL","name":"Melbourne Airport","distance":"25km","transferTime":"35 mins"},{"code":"AVV","name":"Avalon Airport","distance":"55km","transferTime":"50 mins"}]'::jsonb,
    'Melbourne',
    '-37.8497',
    '144.9689',
    '{"race":"2025-03-23 15:00","practice1":"2025-03-21 12:30","practice2":"2025-03-21 16:00","practice3":"2025-03-22 14:00","qualifying":"2025-03-22 17:00"}'::jsonb,
    '{"price":0,"title":"","general":{"price":"150","availability":"medium"},"grandstand":{"price":"450","availability":"high"},"ticketType":"3_DAY","description":"","resellerUrl":"","availability":"available","daysIncluded":{"friday":true,"sunday":true,"saturday":true,"thursday":false},"isChildTicket":false}'::jsonb,
    '{"length":"5.278 km","corners":14,"drsZones":4,"lapRecord":{"time":"1:20.235","year":2023,"driver":"Sergio Perez"}}'::jsonb,
    '{"first":{"team":"Red Bull Racing","driver":"Max Verstappen"},"third":{"team":"Aston Martin","driver":"Fernando Alonso"},"second":{"team":"Mercedes","driver":"Lewis Hamilton"}}'::jsonb,
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Australia_Circuit.png',
    'upcoming',
    'australian-grand-prix-2025',
    '[{"id":"1","name":"City Walking Tour","type":"guided","price":{"amount":30,"currency":"USD"},"rating":4.5,"category":"cultural","distance":"2 km from circuit","duration":"2.5 hr","location":{"lat":40.7128,"lng":-74.006},"description":"Explore historic landmarks and architecture"},{"id":"2","name":"Karting Experience","type":"activity","price":{"amount":45,"currency":"USD"},"rating":4.8,"category":"sports","distance":"5 km from circuit","duration":"1.5 hr","location":{"lat":40.7228,"lng":-74.016},"description":"Race on a professional karting circuit"},{"id":"3","name":"Local Food Tour","type":"guided","price":{"amount":55,"currency":"USD"},"rating":4.6,"category":"dining","distance":"1.5 km from circuit","duration":"3 hr","location":{"lat":40.7328,"lng":-74.026},"description":"Taste authentic local cuisine and street food"},{"id":"4","name":"Racing Museum","type":"attraction","price":{"amount":25,"currency":"USD"},"rating":4.3,"category":"entertainment","distance":"3 km from circuit","duration":"2 hr","location":{"lat":40.7428,"lng":-74.036},"description":"Learn about local motorsport history"},{"id":"5","name":"Motorsport Mall","type":"shopping","price":{"amount":0,"currency":"USD"},"rating":4.2,"category":"shopping","distance":"4 km from circuit","duration":"1.5 hr","location":{"lat":40.7528,"lng":-74.046},"description":"F1 merchandise and local souvenirs"}]'::jsonb,
    '[]'::jsonb,
    'available',
    4766.00,
    'spring',
    '[{"round":1,"series":"F2"},{"round":1,"series":"F3"}]'::jsonb,
    false,
    '2025-03-14T00:00:00.000Z',
    '2025-03-16T00:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    25,
    'Abu Dhabi Grand Prix 2025',
    'Yas Marina Circuit',
    'United Arab Emirates',
    '2025-12-05T00:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Abu_Dhabi.jpg',
    'Season finale at the spectacular day-to-night race in Abu Dhabi.',
    '{"taxi":"Available at airport and circuit","shuttle":"Hotel shuttle services"}'::jsonb,
    '{"humidity":"60%","rainfall":"Low","averageTemp":"26°C"}'::jsonb,
    '[{"code":"AUH","name":"Abu Dhabi International Airport","distance":"15km","transferTime":"20-30 minutes"}]'::jsonb,
    'Abu Dhabi',
    '24.4672',
    '54.6031',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"5.281","corners":16,"drsZones":2,"lapRecord":{"time":"1:26.103","year":2021,"driver":"Max Verstappen"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"Ferrari","driver":"Charles Leclerc","position":2},{"team":"Mercedes","driver":"George Russell","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Ferrari World","description":"Ferrari-themed amusement park"},{"name":"Yas Beach","description":"Private beach club"}]'::jsonb,
    '[]'::jsonb,
    'sold_out',
    1148.00,
    'winter',
    '[{"round":18,"series":"F2"},{"round":9,"series":"F1 Academy"}]'::jsonb,
    false,
    '2025-12-03T00:00:00.000Z',
    '2025-12-07T00:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    2,
    'Belgian Grand Prix 2025',
    'Circuit de Spa-Francorchamps',
    'Belgium',
    '2025-07-24T23:00:00.000Z',
    'https://images.unsplash.com/photo-1589556264800-08ae9e129a8c',
    'Race through the legendary Spa-Francorchamps circuit in the heart of the Ardennes forest.',
    '{"parking":"Multiple parking areas with shuttle service","public_transport":{"bus":"Special race weekend shuttle services","train":"Verviers-Central is the nearest major station"}}'::jsonb,
    '{"typical":{"august":{"temp_low":13,"temp_high":23,"conditions":"Unpredictable, famous for micro-climate"}}}'::jsonb,
    '[{"code":"BRU","name":"Brussels Airport","distance":"120km","transferTime":"1.5 hours"},{"code":"LGG","name":"Liège Airport","distance":"60km","transferTime":"1 hour"}]'::jsonb,
    NULL,
    '50.4372',
    '5.9714',
    '{}'::jsonb,
    '{"general":{"price":"150","availability":"medium"},"grandstand":{"price":"450","availability":"high"}}'::jsonb,
    '{"length":"7.004 km","corners":19,"drsZones":2,"lapRecord":{"time":"1:46.286","year":2023,"driver":"Max Verstappen"}}'::jsonb,
    '{}'::jsonb,
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Belgium_Circuit.png',
    'upcoming',
    'belgian-grand-prix',
    '[{"id":"1","name":"City Walking Tour","type":"guided","price":{"amount":30,"currency":"USD"},"rating":4.5,"category":"cultural","distance":"2 km from circuit","duration":"2.5 hr","location":{"lat":40.7128,"lng":-74.006},"description":"Explore historic landmarks and architecture"},{"id":"2","name":"Karting Experience","type":"activity","price":{"amount":45,"currency":"USD"},"rating":4.8,"category":"sports","distance":"5 km from circuit","duration":"1.5 hr","location":{"lat":40.7228,"lng":-74.016},"description":"Race on a professional karting circuit"},{"id":"3","name":"Local Food Tour","type":"guided","price":{"amount":55,"currency":"USD"},"rating":4.6,"category":"dining","distance":"1.5 km from circuit","duration":"3 hr","location":{"lat":40.7328,"lng":-74.026},"description":"Taste authentic local cuisine and street food"},{"id":"4","name":"Racing Museum","type":"attraction","price":{"amount":25,"currency":"USD"},"rating":4.3,"category":"entertainment","distance":"3 km from circuit","duration":"2 hr","location":{"lat":40.7428,"lng":-74.036},"description":"Learn about local motorsport history"},{"id":"5","name":"Motorsport Mall","type":"shopping","price":{"amount":0,"currency":"USD"},"rating":4.2,"category":"shopping","distance":"4 km from circuit","duration":"1.5 hr","location":{"lat":40.7528,"lng":-74.046},"description":"F1 merchandise and local souvenirs"}]'::jsonb,
    '[]'::jsonb,
    'available',
    6707.00,
    'summer',
    '[{"round":11,"series":"F2"},{"round":8,"series":"F3"},{"round":13,"series":"F1 Sprint"}]'::jsonb,
    true,
    '2025-07-22T23:00:00.000Z',
    '2025-07-26T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    27,
    'Qatar Grand Prix 2025',
    'Lusail International Circuit',
    'Qatar',
    '2025-11-30T00:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Qatar.jpg',
    'Night race at the state-of-the-art Lusail International Circuit',
    '{"taxi":"Available at airport and circuit","shuttle":"Regular service from Doha"}'::jsonb,
    '{"humidity":"60%","rainfall":"Low","averageTemp":"25°C"}'::jsonb,
    '[{"code":"DOH","name":"Hamad International Airport","distance":"30km","transferTime":"30-40 minutes"}]'::jsonb,
    'Lusail',
    '25.4866',
    '51.4534',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"5.419 km","corners":16,"drsZones":1,"lapRecord":{"time":"1:24.319","year":2023,"driver":"Max Verstappen"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"McLaren","driver":"Oscar Piastri","position":2},{"team":"McLaren","driver":"Lando Norris","position":3}]'::jsonb,
    NULL,
    'upcoming',
    'qatar-grand-prix-2025',
    '[{"name":"National Museum of Qatar","description":"Architectural masterpiece showcasing Qatar''s history"},{"name":"Katara Cultural Village","description":"Cultural and entertainment destination"}]'::jsonb,
    '[]'::jsonb,
    'available',
    2999.00,
    'fall',
    '[{"round":13,"series":"F2"},{"round":23,"series":"F1 Sprint"}]'::jsonb,
    true,
    '2025-11-28T00:00:00.000Z',
    '2025-11-30T00:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    1,
    'British Grand Prix 2025',
    'Silverstone Circuit',
    'United Kingdom',
    '2025-07-05T23:00:00.000Z',
    'https://images.unsplash.com/photo-1642888622502-3899916ddc7c',
    'Experience the historic British Grand Prix at Silverstone, home of British motorsport.',
    '{"parking":"Multiple parking zones available around the circuit","public_transport":{"bus":"Regular shuttle services from nearby towns","train":"Nearest stations are Milton Keynes Central and Northampton"}}'::jsonb,
    '{"typical":{"july":{"temp_low":12,"temp_high":22,"conditions":"Variable, chances of rain"}}}'::jsonb,
    '[{"code":"LHR","name":"London Heathrow","distance":"85 miles","transferTime":"2 hours"},{"code":"BHX","name":"Birmingham","distance":"60 miles","transferTime":"1.5 hours"}]'::jsonb,
    NULL,
    '52.0733',
    '-1.0146',
    '{}'::jsonb,
    '{"general":{"price":"150","availability":"medium"},"grandstand":{"price":"450","availability":"high"}}'::jsonb,
    '{"length":"5.891 km","corners":18,"drsZones":2,"lapRecord":{"time":"1:27.097","year":2023,"driver":"Max Verstappen"}}'::jsonb,
    '{}'::jsonb,
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Great_Britain_Circuit.png',
    'upcoming',
    'british-grand-prix',
    '[{"id":"1","name":"City Walking Tour","type":"guided","price":{"amount":30,"currency":"USD"},"rating":4.5,"category":"cultural","distance":"2 km from circuit","duration":"2.5 hr","location":{"lat":40.7128,"lng":-74.006},"description":"Explore historic landmarks and architecture"},{"id":"2","name":"Karting Experience","type":"activity","price":{"amount":45,"currency":"USD"},"rating":4.8,"category":"sports","distance":"5 km from circuit","duration":"1.5 hr","location":{"lat":40.7228,"lng":-74.016},"description":"Race on a professional karting circuit"},{"id":"3","name":"Local Food Tour","type":"guided","price":{"amount":55,"currency":"USD"},"rating":4.6,"category":"dining","distance":"1.5 km from circuit","duration":"3 hr","location":{"lat":40.7328,"lng":-74.026},"description":"Taste authentic local cuisine and street food"},{"id":"4","name":"Racing Museum","type":"attraction","price":{"amount":25,"currency":"USD"},"rating":4.3,"category":"entertainment","distance":"3 km from circuit","duration":"2 hr","location":{"lat":40.7428,"lng":-74.036},"description":"Learn about local motorsport history"},{"id":"5","name":"Motorsport Mall","type":"shopping","price":{"amount":0,"currency":"USD"},"rating":4.2,"category":"shopping","distance":"4 km from circuit","duration":"1.5 hr","location":{"lat":40.7528,"lng":-74.046},"description":"F1 merchandise and local souvenirs"}]'::jsonb,
    '[]'::jsonb,
    'sold_out',
    2401.00,
    'summer',
    '[{"round":10,"series":"F2"},{"round":7,"series":"F3"}]'::jsonb,
    false,
    '2025-07-03T23:00:00.000Z',
    '2025-07-05T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    21,
    'United States Grand Prix 2025',
    'Circuit of The Americas',
    'United States',
    '2025-10-24T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/United_States.jpg',
    'Modern circuit inspired by the best corners from around the world.',
    '{"shuttle":"Regular service from downtown Austin","rideshare":"Dedicated pickup zones"}'::jsonb,
    '{"humidity":"65%","rainfall":"Low","averageTemp":"22°C"}'::jsonb,
    '[{"code":"AUS","name":"Austin-Bergstrom International Airport","distance":"15km","transferTime":"20-30 minutes"}]'::jsonb,
    'Austin',
    '30.1328',
    '-97.6411',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"5.513","corners":20,"drsZones":2,"lapRecord":{"time":"1:36.169","year":2019,"driver":"Charles Leclerc"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"Mercedes","driver":"Lewis Hamilton","position":2},{"team":"McLaren","driver":"Lando Norris","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Austin 6th Street","description":"Entertainment district"},{"name":"Texas State Capitol","description":"Historic government building"}]'::jsonb,
    '[]'::jsonb,
    'available',
    2245.00,
    'fall',
    '[{"round":19,"series":"F1 Sprint"}]'::jsonb,
    true,
    '2025-10-23T23:00:00.000Z',
    '2025-10-25T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    4,
    'Saudi Arabian Grand Prix 2025',
    'Jeddah Corniche Circuit',
    'Saudi Arabia',
    '2025-04-19T22:00:00.000Z',
    'https://picsum.photos/1920/1080',
    'Night race through the streets of Jeddah',
    '{"public":{"options":[],"description":""},"parking":{"options":[],"description":""}}'::jsonb,
    '{"practice1":{"humidity":"65","windSpeed":"12","conditions":"Clear","temperature":"26","precipitation":"0"}}'::jsonb,
    '[{"code":"JED","name":"King Abdulaziz International","distance":"15km","transferTime":"25 mins"}]'::jsonb,
    'Jeddah',
    '21.6319',
    '39.1044',
    '{"race":"2025-03-09 20:00","practice1":"2025-03-07 13:30","practice2":"2025-03-07 17:00","practice3":"2025-03-08 14:30","qualifying":"2025-03-08 18:00"}'::jsonb,
    '{"general":{"price":"150","availability":"medium"},"grandstand":{"price":"450","availability":"high"}}'::jsonb,
    '{"length":"6.174 km","corners":27,"drsZones":3,"lapRecord":{"time":"1:30.734","year":2021,"driver":"Lewis Hamilton"}}'::jsonb,
    '{"first":{"team":"Red Bull Racing","driver":"Sergio Perez"},"third":{"team":"Aston Martin","driver":"Fernando Alonso"},"second":{"team":"Red Bull Racing","driver":"Max Verstappen"}}'::jsonb,
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Saudi_Arabia_Circuit.png',
    'upcoming',
    'saudi-arabian-grand-prix-2025',
    '[{"id":"1","name":"City Walking Tour","type":"guided","price":{"amount":30,"currency":"USD"},"rating":4.5,"category":"cultural","distance":"2 km from circuit","duration":"2.5 hr","location":{"lat":40.7128,"lng":-74.006},"description":"Explore historic landmarks and architecture"},{"id":"2","name":"Karting Experience","type":"activity","price":{"amount":45,"currency":"USD"},"rating":4.8,"category":"sports","distance":"5 km from circuit","duration":"1.5 hr","location":{"lat":40.7228,"lng":-74.016},"description":"Race on a professional karting circuit"},{"id":"3","name":"Local Food Tour","type":"guided","price":{"amount":55,"currency":"USD"},"rating":4.6,"category":"dining","distance":"1.5 km from circuit","duration":"3 hr","location":{"lat":40.7328,"lng":-74.026},"description":"Taste authentic local cuisine and street food"},{"id":"4","name":"Racing Museum","type":"attraction","price":{"amount":25,"currency":"USD"},"rating":4.3,"category":"entertainment","distance":"3 km from circuit","duration":"2 hr","location":{"lat":40.7428,"lng":-74.036},"description":"Learn about local motorsport history"},{"id":"5","name":"Motorsport Mall","type":"shopping","price":{"amount":0,"currency":"USD"},"rating":4.2,"category":"shopping","distance":"4 km from circuit","duration":"1.5 hr","location":{"lat":40.7528,"lng":-74.046},"description":"F1 merchandise and local souvenirs"}]'::jsonb,
    '[]'::jsonb,
    'available',
    2811.00,
    'spring',
    '[{"round":3,"series":"F2"},{"round":2,"series":"F1 Academy"}]'::jsonb,
    false,
    '2025-04-17T23:00:00.000Z',
    '2025-04-19T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    29,
    'Spanish Grand Prix 2025',
    'Circuit de Barcelona-Catalunya',
    'Spain',
    '2025-05-30T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Spain_Circuit.png',
    'Racing at the historic Circuit de Barcelona-Catalunya',
    '{"public":"Metro and bus services available","parking":"Available at circuit"}'::jsonb,
    '{"rainfall":"Low","averageTemp":"22°C"}'::jsonb,
    '[{"code":"BCN","name":"Barcelona–El Prat Airport","distance":"25km"}]'::jsonb,
    'Barcelona',
    '41.57',
    '2.26',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"4.675 km","corners":16,"drsZones":2}'::jsonb,
    '[]'::jsonb,
    NULL,
    'upcoming',
    'spanish-grand-prix-2025',
    '[]'::jsonb,
    '[]'::jsonb,
    'available',
    1500.00,
    'spring',
    '[{"round":6,"series":"F2"},{"round":5,"series":"F3"}]'::jsonb,
    false,
    '2025-05-29T23:00:00.000Z',
    '2025-05-31T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    24,
    'Las Vegas Grand Prix 2025',
    'Las Vegas Strip Circuit',
    'United States',
    '2025-11-20T00:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Las_Vegas.jpg',
    'Night race through the neon-lit streets of Las Vegas.',
    '{"shuttle":"Hotel shuttle services","monorail":"Service along the Strip"}'::jsonb,
    '{"humidity":"30%","rainfall":"Low","averageTemp":"12°C"}'::jsonb,
    '[{"code":"LAS","name":"Harry Reid International Airport","distance":"5km","transferTime":"10-15 minutes"}]'::jsonb,
    'Las Vegas',
    '36.1699',
    '-115.1398',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"6.201","corners":17,"drsZones":2,"lapRecord":{"time":"1:35.490","year":2023,"driver":"Max Verstappen"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"Ferrari","driver":"Charles Leclerc","position":2},{"team":"Red Bull Racing","driver":"Sergio Perez","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Bellagio Fountains","description":"Musical water feature"},{"name":"Fremont Street","description":"Historic casino district"}]'::jsonb,
    '[]'::jsonb,
    'limited',
    3281.00,
    'winter',
    '[{"round":17,"series":"F2"}]'::jsonb,
    false,
    '2025-11-18T00:00:00.000Z',
    '2025-11-22T00:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    30,
    'Hungarian Grand Prix 2025',
    'Hungaroring',
    'Hungary',
    '2025-08-01T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Hungary_Circuit.png',
    'Racing at the twisty Hungaroring circuit',
    '{"taxi":"Available from city","shuttle":"Regular service from Budapest"}'::jsonb,
    '{"rainfall":"Medium","averageTemp":"28°C"}'::jsonb,
    '[{"code":"BUD","name":"Budapest Ferenc Liszt International Airport","distance":"20km"}]'::jsonb,
    'Budapest',
    '47.58',
    '19.25',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"4.381 km","corners":14,"drsZones":2}'::jsonb,
    '[]'::jsonb,
    NULL,
    'upcoming',
    'hungarian-grand-prix-2025',
    '[]'::jsonb,
    '[]'::jsonb,
    'available',
    1200.00,
    'summer',
    '[{"round":10,"series":"F2"},{"round":9,"series":"F3"}]'::jsonb,
    false,
    '2025-07-31T23:00:00.000Z',
    '2025-08-02T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    31,
    'Azerbaijan Grand Prix 2025',
    'Baku City Circuit',
    'Azerbaijan',
    '2025-09-19T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Baku_Circuit.png',
    'Street racing in the heart of Baku',
    '{"taxi":"Available throughout city","shuttle":"Service from key hotels"}'::jsonb,
    '{"rainfall":"Low","averageTemp":"24°C"}'::jsonb,
    '[{"code":"GYD","name":"Heydar Aliyev International Airport","distance":"25km"}]'::jsonb,
    'Baku',
    '40.37',
    '49.85',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"6.003 km","corners":20,"drsZones":2}'::jsonb,
    '[]'::jsonb,
    NULL,
    'upcoming',
    'azerbaijan-grand-prix-2025',
    '[]'::jsonb,
    '[]'::jsonb,
    'available',
    1300.00,
    'fall',
    '[{"round":12,"series":"F2"}]'::jsonb,
    false,
    '2025-09-18T23:00:00.000Z',
    '2025-09-20T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    17,
    'Austrian Grand Prix 2025',
    'Red Bull Ring',
    'Austria',
    '2025-07-18T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Austria.jpg',
    'Fast and flowing circuit in the Styrian mountains.',
    '{"parking":"Extensive on-site parking available","shuttle":"Regular service from Knittelfeld station"}'::jsonb,
    '{"humidity":"60%","rainfall":"Moderate","averageTemp":"24°C"}'::jsonb,
    '[{"code":"GRZ","name":"Graz Airport","distance":"85km","transferTime":"60-75 minutes"}]'::jsonb,
    'Spielberg',
    '47.2197',
    '14.7647',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"4.318","corners":10,"drsZones":3,"lapRecord":{"time":"1:05.619","year":2020,"driver":"Carlos Sainz"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"Ferrari","driver":"Charles Leclerc","position":2},{"team":"Red Bull Racing","driver":"Sergio Perez","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Red Bull Ring Museum","description":"Racing history exhibition"},{"name":"Styrian Mountains","description":"Beautiful alpine scenery"}]'::jsonb,
    '[]'::jsonb,
    'limited',
    6723.00,
    'summer',
    '[{"round":9,"series":"F2"},{"round":6,"series":"F3"},{"round":9,"series":"F1 Sprint"}]'::jsonb,
    true,
    '2025-07-17T23:00:00.000Z',
    '2025-07-19T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    19,
    'Italian Grand Prix 2025',
    'Autodromo Nazionale Monza',
    'Italy',
    '2025-09-04T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Italy.jpg',
    'The Temple of Speed - F1''s fastest circuit and a historic racing venue.',
    '{"bus":"Regular service from Milan","train":"Shuttle service from Monza station"}'::jsonb,
    '{"humidity":"70%","rainfall":"Low","averageTemp":"22°C"}'::jsonb,
    '[{"code":"MXP","name":"Milan Malpensa Airport","distance":"45km","transferTime":"45-55 minutes"}]'::jsonb,
    'Monza',
    '45.6156',
    '9.2811',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"5.793","corners":11,"drsZones":2,"lapRecord":{"time":"1:21.046","year":2004,"driver":"Rubens Barrichello"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"Red Bull Racing","driver":"Sergio Perez","position":2},{"team":"Ferrari","driver":"Carlos Sainz","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Monza Park","description":"Historic royal park"},{"name":"Monza Cathedral","description":"Gothic-Romanesque cathedral"}]'::jsonb,
    '[]'::jsonb,
    'available',
    9158.00,
    'fall',
    '[{"round":12,"series":"F2"},{"round":9,"series":"F3"}]'::jsonb,
    false,
    '2025-09-02T23:00:00.000Z',
    '2025-09-06T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    23,
    'São Paulo Grand Prix 2025',
    'Autódromo José Carlos Pace',
    'Brazil',
    '2025-11-22T00:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Brazil.jpg',
    'The historic Interlagos circuit known for unpredictable weather and great racing.',
    '{"taxi":"Available at circuit","metro":"Line 9 to Autódromo station"}'::jsonb,
    '{"humidity":"80%","rainfall":"High","averageTemp":"24°C"}'::jsonb,
    '[{"code":"GRU","name":"São Paulo/Guarulhos International Airport","distance":"25km","transferTime":"45-60 minutes"}]'::jsonb,
    'São Paulo',
    '-23.7036',
    '-46.6997',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"4.309","corners":15,"drsZones":2,"lapRecord":{"time":"1:10.540","year":2018,"driver":"Valtteri Bottas"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"McLaren","driver":"Lando Norris","position":2},{"team":"Aston Martin","driver":"Fernando Alonso","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Ibirapuera Park","description":"Urban park and cultural center"},{"name":"Pinacoteca","description":"Art museum"}]'::jsonb,
    '[]'::jsonb,
    'limited',
    3111.00,
    'fall',
    '[{"round":16,"series":"F2"},{"round":21,"series":"F1 Sprint"}]'::jsonb,
    true,
    '2025-11-21T00:00:00.000Z',
    '2025-11-23T00:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    12,
    'Chinese Grand Prix 2025',
    'Shanghai International Circuit',
    'China',
    '2025-03-23T00:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/China.jpg',
    'Return to Shanghai''s unique layout with its demanding turns.',
    '{"public":{"options":[],"description":""},"parking":{"options":[],"description":""}}'::jsonb,
    '{"humidity":"65%","rainfall":"Light","averageTemp":"18°C"}'::jsonb,
    '[{"code":"PVG","name":"Shanghai Pudong International Airport","distance":"40km","transferTime":"45-60 minutes"}]'::jsonb,
    'Shanghai',
    '31.3389',
    '121.2205',
    '{"race":"","sprint":"","practice1":"","qualifying":"","sprint_qualifying":""}'::jsonb,
    '{}'::jsonb,
    '{"length":"5.451 km","corners":16,"drsZones":2,"lapRecord":{"time":"1:32.238","year":2004,"driver":"Michael Schumacher"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"Ferrari","driver":"Charles Leclerc","position":2},{"team":"Ferrari","driver":"Carlos Sainz","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"id":"aed9a134-e72b-4db7-8994-d3daaaa8bb42","name":"The Bund","type":"attraction","price":{"amount":0,"currency":"USD"},"rating":0,"category":"","distance":"","duration":"","location":{"lat":0,"lng":0},"description":"Famous waterfront area"},{"id":"bb3981fb-776a-49ba-bf10-5e3ab28d6c01","name":"Yu Garden","type":"attraction","price":{"amount":0,"currency":"USD"},"rating":0,"category":"","distance":"","duration":"","location":{"lat":0,"lng":0},"description":"Traditional Chinese garden"}]'::jsonb,
    '[]'::jsonb,
    'available',
    6315.00,
    'spring',
    '[{"round":5,"series":"F2"},{"round":3,"series":"F1 Academy"},{"round":2,"series":"F1 Sprint"}]'::jsonb,
    true,
    '2025-03-21T00:00:00.000Z',
    '2025-03-23T00:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    11,
    'Japanese Grand Prix 2025',
    'Suzuka International Racing Course',
    'Japan',
    '2025-04-05T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Japan.jpg',
    'The legendary figure-8 circuit that has decided many championships.',
    '{"taxi":"Available at airport and circuit","shuttle":"Regular service from Shiroko and Suzuka Circuit Ino stations"}'::jsonb,
    '{"humidity":"70%","rainfall":"Moderate","averageTemp":"20°C"}'::jsonb,
    '[{"code":"NGO","name":"Chubu Centrair International Airport","distance":"85km","transferTime":"75-90 minutes"}]'::jsonb,
    'Suzuka',
    '34.8431',
    '136.5407',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"5.807 km","corners":18,"drsZones":1,"lapRecord":{"time":"1:30.983","year":2019,"driver":"Lewis Hamilton"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"McLaren","driver":"Lando Norris","position":2},{"team":"McLaren","driver":"Oscar Piastri","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Suzuka Circuit Museum","description":"Racing history museum"},{"name":"Nagashima Spa Land","description":"One of Japan''s largest amusement parks"}]'::jsonb,
    '[]'::jsonb,
    'available',
    4482.00,
    'spring',
    '[]'::jsonb,
    false,
    '2025-04-03T23:00:00.000Z',
    '2025-04-05T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    22,
    'Mexico City Grand Prix 2025',
    'Autódromo Hermanos Rodríguez',
    'Mexico',
    '2025-10-25T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Mexico.jpg',
    'High-altitude circuit featuring the unique stadium section.',
    '{"bus":"Special event services","metro":"Line 9 to Ciudad Deportiva station"}'::jsonb,
    '{"humidity":"45%","rainfall":"Low","averageTemp":"20°C"}'::jsonb,
    '[{"code":"MEX","name":"Mexico City International Airport","distance":"10km","transferTime":"15-25 minutes"}]'::jsonb,
    'Mexico City',
    '19.4042',
    '-99.0907',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"4.304","corners":17,"drsZones":3,"lapRecord":{"time":"1:17.774","year":2021,"driver":"Valtteri Bottas"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"Mercedes","driver":"Lewis Hamilton","position":2},{"team":"Ferrari","driver":"Charles Leclerc","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Zócalo","description":"Historic city center"},{"name":"Chapultepec Castle","description":"Hilltop castle and museum"}]'::jsonb,
    '[]'::jsonb,
    'limited',
    3775.00,
    'fall',
    '[]'::jsonb,
    false,
    '2025-10-23T23:00:00.000Z',
    '2025-10-28T00:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    15,
    'Monaco Grand Prix 2025',
    'Circuit de Monaco',
    'Monaco',
    '2025-05-21T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Monaco.jpg',
    'The most prestigious race on the calendar through the streets of Monte Carlo.',
    '{"train":"Regular service to Monaco-Monte Carlo station","helicopter":"Available from Nice Airport"}'::jsonb,
    '{"humidity":"70%","rainfall":"Low","averageTemp":"21°C"}'::jsonb,
    '[{"code":"NCE","name":"Nice Cote d''Azur Airport","distance":"30km","transferTime":"30-40 minutes"}]'::jsonb,
    'Monte Carlo',
    '43.7347',
    '7.4206',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"3.337 km","corners":19,"drsZones":1,"lapRecord":{"time":"1:12.909","year":2021,"driver":"Lewis Hamilton"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"Aston Martin","driver":"Fernando Alonso","position":2},{"team":"Alpine","driver":"Esteban Ocon","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Monte Carlo Casino","description":"World-famous casino and landmark"},{"name":"Prince''s Palace","description":"Official residence of Monaco''s Sovereign Prince"}]'::jsonb,
    '[]'::jsonb,
    'sold_out',
    3025.00,
    'summer',
    '[{"round":8,"series":"F2"},{"round":5,"series":"F3"}]'::jsonb,
    false,
    '2025-05-19T23:00:00.000Z',
    '2025-05-23T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    16,
    'Canadian Grand Prix 2025',
    'Circuit Gilles Villeneuve',
    'Canada',
    '2025-06-20T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Canada.jpg',
    'Fast circuit on the Île Notre-Dame in the St. Lawrence River.',
    '{"metro":"Direct service to Jean-Drapeau station","shuttle":"Water taxi service available"}'::jsonb,
    '{"humidity":"65%","rainfall":"Moderate","averageTemp":"23°C"}'::jsonb,
    '[{"code":"YUL","name":"Montréal-Pierre Elliott Trudeau International Airport","distance":"20km","transferTime":"25-35 minutes"}]'::jsonb,
    'Montreal',
    '45.5017',
    '-73.5228',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"4.361 km","corners":14,"drsZones":2,"lapRecord":{"time":"1:13.078","year":2019,"driver":"Valtteri Bottas"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"Aston Martin","driver":"Fernando Alonso","position":2},{"team":"Mercedes","driver":"Lewis Hamilton","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Old Montreal","description":"Historic district with cobblestone streets"},{"name":"Mount Royal","description":"Park offering panoramic city views"}]'::jsonb,
    '[]'::jsonb,
    'available',
    7506.00,
    'summer',
    '[{"round":5,"series":"F1 Academy"}]'::jsonb,
    false,
    '2025-06-19T23:00:00.000Z',
    '2025-06-21T23:00:00.000Z'
  );
INSERT INTO races_old VALUES (
    18,
    'Dutch Grand Prix 2025',
    'Circuit Zandvoort',
    'Netherlands',
    '2025-08-28T23:00:00.000Z',
    'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Netherlands.jpg',
    'Seaside circuit with banked corners and passionate orange-clad fans.',
    '{"train":"Direct service to Zandvoort aan Zee station","bicycle":"Dedicated cycling routes available"}'::jsonb,
    '{"humidity":"75%","rainfall":"Moderate","averageTemp":"18°C"}'::jsonb,
    '[{"code":"AMS","name":"Amsterdam Airport Schiphol","distance":"30km","transferTime":"30-40 minutes"}]'::jsonb,
    'Zandvoort',
    '52.3888',
    '4.5409',
    '{}'::jsonb,
    '{}'::jsonb,
    '{"length":"4.259","corners":14,"drsZones":2,"lapRecord":{"time":"1:11.097","year":2021,"driver":"Lewis Hamilton"}}'::jsonb,
    '[{"team":"Red Bull Racing","driver":"Max Verstappen","position":1},{"team":"Aston Martin","driver":"Fernando Alonso","position":2},{"team":"Alpine","driver":"Pierre Gasly","position":3}]'::jsonb,
    NULL,
    'upcoming',
    NULL,
    '[{"name":"Zandvoort Beach","description":"Popular coastal resort"},{"name":"Circuit Museum","description":"Racing heritage exhibition"}]'::jsonb,
    '[]'::jsonb,
    'available',
    2854.00,
    'fall',
    '[{"round":5,"series":"F1 Academy"}]'::jsonb,
    false,
    '2025-08-26T23:00:00.000Z',
    '2025-08-30T23:00:00.000Z'
  );
INSERT INTO saved_itineraries_old VALUES (
    11,
    4,
    1,
    'Hellom8',
    '[{"id":"4","name":"Racing Museum","type":"attraction","price":{"amount":25,"currency":"USD"},"rating":4.3,"category":"entertainment","distance":"3 km from circuit","duration":"2 hr hours","location":{"lat":40.7428,"lng":-74.036},"timeSlot":"09:30 AM","description":"Learn about local motorsport history","visitDuration":"2 hr hours"},{"id":"3","name":"Local Food Tour","type":"guided","price":{"amount":55,"currency":"USD"},"rating":4.6,"category":"dining","distance":"1.5 km from circuit","duration":"3 hr hours","location":{"lat":40.7328,"lng":-74.026},"timeSlot":"12:00 PM","description":"Taste authentic local cuisine and street food","visitDuration":"3 hr hours"}]'::jsonb,
    '2024-12-09T19:31:23.529Z',
    NULL,
    '2024-12-12T12:00:00.000Z'
  );
INSERT INTO saved_itineraries_old VALUES (
    12,
    2,
    1,
    'new itinerary',
    '[{"id":"1","name":"City Walking Tour","type":"guided","price":{"amount":30,"currency":"USD"},"rating":4.5,"category":"cultural","distance":"2 km from circuit","duration":"2.5 hr","location":{"lat":40.7128,"lng":-74.006},"timeSlot":"10:30","description":"Explore historic landmarks and architecture"},{"id":"2","name":"Karting Experience","type":"activity","price":{"amount":45,"currency":"USD"},"rating":4.8,"category":"sports","distance":"5 km from circuit","duration":"1.5 hr","location":{"lat":40.7228,"lng":-74.016},"timeSlot":"14:00","description":"Race on a professional karting circuit"}]'::jsonb,
    '2024-12-09T22:24:26.114Z',
    NULL,
    '2024-12-10T01:53:05.534Z'
  );
INSERT INTO saved_itineraries_old VALUES (
    2,
    4,
    1,
    'Test',
    '[{"id":"3","name":"Local Food Tour","type":"guided","price":{"amount":55,"currency":"USD"},"rating":4.6,"category":"dining","distance":"1.5 km from circuit","duration":"3 hr","location":{"lat":40.7328,"lng":-74.026},"timeSlot":"09:30","travelTime":{"fromCircuit":"15 min from circuit","fromPrevious":"10 min travel time"},"description":"Taste authentic local cuisine and street food"},{"id":"1","name":"City Walking Tour","type":"guided","price":{"amount":30,"currency":"USD"},"rating":4.5,"category":"cultural","distance":"2 km from circuit","duration":"2.5 hr","location":{"lat":40.7128,"lng":-74.006},"timeSlot":"13:00","travelTime":{"fromCircuit":"15 min from circuit","fromPrevious":"10 min travel time"},"description":"Explore historic landmarks and architecture"}]'::jsonb,
    '2024-12-09T08:51:27.497Z',
    NULL,
    '2024-12-10T01:53:05.534Z'
  );
INSERT INTO saved_itineraries_old VALUES (
    5,
    4,
    1,
    'testing',
    '[{"id":"2","name":"Karting Experience","distance":"5 km from circuit","timeSlot":"1:00 PM","description":"Race on a professional karting circuit"},{"id":"4","name":"Racing Museum","distance":"3 km from circuit","timeSlot":"09:00 AM","description":"Learn about local motorsport history"}]'::jsonb,
    '2024-12-09T09:23:24.554Z',
    NULL,
    '2024-12-10T01:53:05.534Z'
  );
INSERT INTO saved_itineraries_old VALUES (
    8,
    2,
    1,
    'tes6',
    '[{"id":"5","name":"Motorsport Mall","distance":"4 km from circuit","timeSlot":"09:00 AM","description":"F1 merchandise and local souvenirs"},{"id":"3","name":"Local Food Tour","distance":"1.5 km from circuit","timeSlot":"11:00 AM","description":"Taste authentic local cuisine and street food"}]'::jsonb,
    '2024-12-09T10:16:07.148Z',
    NULL,
    '2024-12-10T01:53:05.534Z'
  );
INSERT INTO saved_itineraries_old VALUES (
    6,
    2,
    1,
    'test3',
    '[{"id":"1","name":"City Walking Tour","distance":"2 km from circuit","timeSlot":"10:00 AM","description":"Explore historic landmarks and architecture"},{"id":"4","name":"Racing Museum","distance":"3 km from circuit","timeSlot":"3:00 PM","description":"Learn about local motorsport history"}]'::jsonb,
    '2024-12-09T09:42:31.823Z',
    NULL,
    '2024-12-10T01:53:05.534Z'
  );
INSERT INTO saved_itineraries_old VALUES (
    7,
    4,
    1,
    'Test4',
    '[{"id":"1","name":"City Walking Tour","distance":"2 km from circuit","timeSlot":"09:00 AM","description":"Explore historic landmarks and architecture"},{"id":"4","name":"Racing Museum","distance":"3 km from circuit","timeSlot":"1:00 PM","description":"Learn about local motorsport history"}]'::jsonb,
    '2024-12-09T09:46:30.004Z',
    NULL,
    '2024-12-10T01:53:05.534Z'
  );
INSERT INTO saved_itineraries_old VALUES (
    9,
    4,
    1,
    'test7',
    '[{"id":"2","name":"Karting Experience","distance":"5 km from circuit","timeSlot":"09:00 AM","description":"Race on a professional karting circuit"},{"id":"4","name":"Racing Museum","distance":"3 km from circuit","timeSlot":"1:00 PM","description":"Learn about local motorsport history"}]'::jsonb,
    '2024-12-09T10:18:36.737Z',
    NULL,
    '2024-12-10T01:53:05.534Z'
  );
INSERT INTO saved_itineraries_old VALUES (
    13,
    4,
    1,
    'lasttest',
    '[{"id":"2","name":"Karting Experience","type":"activity","price":{"amount":45,"currency":"USD"},"rating":4.8,"category":"sports","distance":"5 km from circuit","duration":"1.5 hr","location":{"lat":40.7228,"lng":-74.016},"timeSlot":"10:30","description":"Race on a professional karting circuit"},{"id":"3","name":"Local Food Tour","type":"guided","price":{"amount":55,"currency":"USD"},"rating":4.6,"category":"dining","distance":"1.5 km from circuit","duration":"3 hr","location":{"lat":40.7328,"lng":-74.026},"timeSlot":"12:15","description":"Taste authentic local cuisine and street food"}]'::jsonb,
    '2024-12-10T01:59:51.624Z',
    NULL,
    '2024-12-13T12:00:00.000Z'
  );
INSERT INTO saved_itineraries_old VALUES (
    4,
    4,
    1,
    'test',
    '[{"id":"1","name":"City Walking Tour","distance":"2 km from circuit","timeSlot":"09:00 AM","description":"Explore historic landmarks and architecture"},{"id":"3","name":"Local Food Tour","distance":"1.5 km from circuit","timeSlot":"1:00 PM","description":"Taste authentic local cuisine and street food"},{"id":"5","name":"Motorsport Mall","distance":"4 km from circuit","timeSlot":"5:00 PM","description":"F1 merchandise and local souvenirs"}]'::jsonb,
    '2024-12-09T09:20:51.820Z',
    NULL,
    '2024-12-12T12:00:00.000Z'
  );

-- First, insert the circuits data
INSERT INTO circuits (name, location, country, latitude, longitude)
SELECT DISTINCT 
    circuit,
    COALESCE(city, 'Unknown'),
    country,
    CAST(NULLIF(latitude, '') AS NUMERIC(10,7)),
    CAST(NULLIF(longitude, '') AS NUMERIC(10,7))
FROM races_old
WHERE circuit IS NOT NULL;

-- Insert races data
INSERT INTO races (id, name, country, date, season, round, circuit_id)
SELECT 
    gen_random_uuid(),
    ro.name,
    ro.country,
    ro.date,
    EXTRACT(YEAR FROM ro.date),
    ROW_NUMBER() OVER (PARTITION BY EXTRACT(YEAR FROM ro.date) ORDER BY ro.date),
    c.id
FROM races_old ro
JOIN circuits c ON ro.circuit = c.name;

-- Insert saved itineraries
INSERT INTO saved_itineraries (id, user_id, race_id, itinerary, created_at, updated_at)
SELECT 
    si.id,
    si.user_id::text,
    r.id as race_id,
    '[]'::jsonb as itinerary,
    si.created_at,
    si.date as updated_at
FROM saved_itineraries_old si
JOIN races_old ro ON si.race_id = ro.id
JOIN races r ON r.name = ro.name;

-- Insert activities
INSERT INTO activities (
    itinerary_id,
    name,
    type,
    price_amount,
    price_currency,
    rating,
    category,
    distance,
    duration,
    location_lat,
    location_lng,
    time_slot,
    description,
    visit_duration
)
SELECT 
    si.id as itinerary_id,
    COALESCE((a->>'name')::text, 'Unknown') as name,
    COALESCE((a->>'type')::text, 'other') as type,
    CAST(NULLIF((a->'price'->>'amount')::text, '') AS DECIMAL(10,2)),
    (a->'price'->>'currency')::text as price_currency,
    CAST(NULLIF((a->>'rating')::text, '') AS DECIMAL(3,1)),
    COALESCE((a->>'category')::text, 'other') as category,
    COALESCE((a->>'distance')::text, 'Unknown') as distance,
    COALESCE((a->>'duration')::text, 'Unknown') as duration,
    CAST(NULLIF((a->'location'->>'lat')::text, '') AS DECIMAL(10,8)),
    CAST(NULLIF((a->'location'->>'lng')::text, '') AS DECIMAL(11,8)),
    COALESCE((a->>'timeSlot')::text, 'Unknown') as time_slot,
    COALESCE((a->>'description')::text, 'No description available') as description,
    COALESCE((a->>'visitDuration')::text, 'Unknown') as visit_duration
FROM saved_itineraries_old si
CROSS JOIN LATERAL jsonb_array_elements(si.activities) as a
WHERE si.activities IS NOT NULL AND si.activities != 'null'::jsonb;

-- Insert airports data
INSERT INTO airports (circuit_id, code, name, distance, transfer_time)
SELECT DISTINCT
    c.id as circuit_id,
    COALESCE((a->>'code')::text, 'Unknown') as code,
    COALESCE((a->>'name')::text, 'Unknown') as name,
    COALESCE((a->>'distance')::text, 'Unknown') as distance,
    COALESCE((a->>'transferTime')::text, 'Unknown') as transfer_time
FROM races_old r
CROSS JOIN LATERAL jsonb_array_elements(r.nearest_airports) as a
JOIN circuits c ON r.circuit = c.name
WHERE r.nearest_airports IS NOT NULL AND r.nearest_airports != 'null'::jsonb;

-- Insert circuit details
INSERT INTO circuit_details (circuit_id, length, corners, drs_zones, lap_record_time, lap_record_year, lap_record_driver)
SELECT DISTINCT
    c.id as circuit_id,
    CAST(REGEXP_REPLACE((r.circuit_info->>'length')::text, '[^0-9.]', '', 'g') AS DECIMAL(10,3)),
    CAST((r.circuit_info->>'corners')::text AS INTEGER),
    CAST((r.circuit_info->>'drsZones')::text AS INTEGER),
    ((r.circuit_info->'lapRecord'->>'time')::text),
    CAST((r.circuit_info->'lapRecord'->>'year')::text AS INTEGER),
    ((r.circuit_info->'lapRecord'->>'driver')::text)
FROM races_old r
JOIN circuits c ON r.circuit = c.name
WHERE r.circuit_info IS NOT NULL AND r.circuit_info != 'null'::jsonb;

-- Insert podium results
INSERT INTO podium_results (circuit_id, position, driver, team, year)
SELECT 
    c.id as circuit_id,
    1 as position,
    (r.last_year_podium->'first'->>'driver')::text as driver,
    (r.last_year_podium->'first'->>'team')::text as team,
    EXTRACT(YEAR FROM r.date) as year
FROM races_old r
JOIN circuits c ON r.circuit = c.name
WHERE r.last_year_podium IS NOT NULL AND r.last_year_podium != 'null'::jsonb
AND r.last_year_podium->'first' IS NOT NULL
UNION ALL
SELECT 
    c.id as circuit_id,
    2 as position,
    (r.last_year_podium->'second'->>'driver')::text as driver,
    (r.last_year_podium->'second'->>'team')::text as team,
    EXTRACT(YEAR FROM r.date) as year
FROM races_old r
JOIN circuits c ON r.circuit = c.name
WHERE r.last_year_podium IS NOT NULL AND r.last_year_podium != 'null'::jsonb
AND r.last_year_podium->'second' IS NOT NULL
UNION ALL
SELECT 
    c.id as circuit_id,
    3 as position,
    (r.last_year_podium->'third'->>'driver')::text as driver,
    (r.last_year_podium->'third'->>'team')::text as team,
    EXTRACT(YEAR FROM r.date) as year
FROM races_old r
JOIN circuits c ON r.circuit = c.name
WHERE r.last_year_podium IS NOT NULL AND r.last_year_podium != 'null'::jsonb
AND r.last_year_podium->'third' IS NOT NULL;

-- Insert local attractions
INSERT INTO local_attractions (circuit_id, name, description)
SELECT DISTINCT
    c.id as circuit_id,
    (a->>'name')::text as name,
    (a->>'description')::text as description
FROM races_old r
CROSS JOIN LATERAL jsonb_array_elements(r.local_attractions) as a
JOIN circuits c ON r.circuit = c.name
WHERE r.local_attractions IS NOT NULL AND r.local_attractions != 'null'::jsonb;

-- Insert supporting series
INSERT INTO supporting_series (race_id, series, round)
SELECT 
    r2.id as race_id,
    (s->>'series')::text as series,
    CAST((s->>'round')::text AS INTEGER) as round
FROM races_old r
CROSS JOIN LATERAL jsonb_array_elements(r.supporting_series) as s
JOIN races r2 ON r2.name = r.name
WHERE r.supporting_series IS NOT NULL AND r.supporting_series != 'null'::jsonb;

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_airports_circuit_id ON airports(circuit_id);
CREATE INDEX IF NOT EXISTS idx_airports_code ON airports(code);

CREATE INDEX IF NOT EXISTS idx_circuit_details_circuit_id ON circuit_details(circuit_id);

CREATE INDEX IF NOT EXISTS idx_podium_results_circuit_id ON podium_results(circuit_id);
CREATE INDEX IF NOT EXISTS idx_podium_results_driver ON podium_results(driver);
CREATE INDEX IF NOT EXISTS idx_podium_results_team ON podium_results(team);
CREATE INDEX IF NOT EXISTS idx_podium_results_year ON podium_results(year);

CREATE INDEX IF NOT EXISTS idx_local_attractions_circuit_id ON local_attractions(circuit_id);

CREATE INDEX IF NOT EXISTS idx_supporting_series_race_id ON supporting_series(race_id);
CREATE INDEX IF NOT EXISTS idx_supporting_series_series ON supporting_series(series);

CREATE INDEX IF NOT EXISTS idx_activities_itinerary_id ON activities(itinerary_id);
CREATE INDEX IF NOT EXISTS idx_activities_type ON activities(type);
CREATE INDEX IF NOT EXISTS idx_activities_category ON activities(category);

-- Drop temporary tables
DROP TABLE IF EXISTS races_old;
DROP TABLE IF EXISTS saved_itineraries_old;
